logging:
  file: PYMLModelService.log
  level:
    org.springframework: ERROR
    io.pivotal: DEBUG 
    org.springframework.jdbc.core: TRACE
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
          
  
spring:
  application:
    name:  PLPython Model client Application
  
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false  
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    
server:
    port: 8090

modeldb-datasource:
  jdbc-url: 
  username: 
  password: 
  driverClassName: org.postgresql.Driver

containerdb-datasource:
  jdbc-url: jdbc:postgresql://127.0.0.1:5432/madlibdb?stringtype=unspecified
  username: madlibuser
  password: justworks!
  driverClassName: org.postgresql.Driver
  leak-detection-threshold: 3000
  
---
plpyrest:
  modelreposchema: 
  modelrepotable: 
  modelname: 
  modelversion: 
  modeldescription: 
  payloadtable: 
  resultstable: 
  modelschema: 
  modeldriverfunction: 
  modeldriverfunctionreturntype:
  additionalfunctions:
  modelquery: 
  postgreshome: /usr/local/pgsql/bin/
  workdir: /opt/pivotal/plpy-model




#  modelreposchema: pyml
#  modelrepotable: pyml_model_repo
#  modelname: employee_salary_simple_linear_regression
#  modelversion: 1
#  modeldescription: linear regression model with 1 dependent variable demo
#  payloadtable: employee_salary_predict_model_input
#  resultstable: employee_salary_predict_model_output
#  modelschema: plcpymldemo
#  modeldriverfunction: employee_salary_lr_model_driver
#  modeldriverfunctionreturntype:
#  additionalfunctions:
#  modelquery: select plcpymldemo.employee_salary_lr_model_driver('employee_salary_simple_linear_regression', 1, 'plcpymldemo.employee_salary_predict_model_input','plcpymldemo.employee_salary_predict_model_output')
#  postgreshome: /usr/lib/postgresql/10/bin
#  workdir: /opt/pivotal/plpy-model


  
  